# Generated by Django 4.0.1 on 2022-01-26 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.CharField(choices=[('SU', 'SUV'), ('CT', 'Compact'), ('CD', 'Cedan'), ('CP', 'Coupe'), ('OT', 'Other')], max_length=2)),
                ('plate_num', models.CharField(max_length=8)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('special_info', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100)),
                ('arrive_date', models.DateTimeField(help_text='Format: 2022-01-01 12:00')),
                ('required_type', models.CharField(choices=[('SU', 'SUV'), ('CT', 'Compact'), ('CD', 'Cedan'), ('CP', 'Coupe'), ('OT', 'Other')], max_length=2)),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('special_requirements', models.CharField(blank=True, max_length=400)),
                ('allow_share', models.BooleanField(default=False)),
                ('driver', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sharer', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sharer_seats', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('O', 'Open'), ('F', 'Comfirmed'), ('C', 'Complete')], default='O', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
